/**********************************************************************
 * Extern for jQuery
 * Generated by http://jmmk.github.io/javascript-externs-generator
 **********************************************************************/
var jQuery = {
  "fn": {
    "textcomplete": {
      "Completer": {
        "defaults": {
          "appendTo": {},
          "className": {},
          "dropdownClassName": {},
          "maxCount": {},
          "zIndex": {},
          "rightEdgeOffset": {}
        }
      },
      "Dropdown": {
        "createElement": function () {}
      },
      "SKIP_DEFAULT": {},
      "KEY_UP": {},
      "KEY_DOWN": {},
      "KEY_ENTER": {},
      "KEY_PAGEUP": {},
      "KEY_PAGEDOWN": {},
      "KEY_ESCAPE": {},
      "Strategy": {
        "parse": function () {}
      },
      "Adapter": function () {},
      "Textarea": function () {},
      "IETextarea": function () {},
      "ContentEditable": function () {},
      "CKEditor": function () {},
      "getCaretCoordinates": function () {}
    }
  },
};
jQuery.prototype = {
  "textcomplete": function () {}
};
jQuery.fn.constructor.prototype = {
  "textcomplete": function () {}
};
jQuery.fn.init.prototype = {
  "textcomplete": function () {}
};
jQuery.fn.textcomplete.Completer.prototype = {
  "id": function () {},
  "option": function () {},
  "strategies": function () {},
  "adapter": function () {},
  "dropdown": function () {},
  "$el": function () {},
  "$iframe": function () {},
  "initialize": function () {},
  "destroy": function () {},
  "deactivate": function () {},
  "trigger": function () {},
  "fire": function () {},
  "register": function () {},
  "select": function () {},
  "_clearAtNext": function () {},
  "_term": function () {},
  "_extractSearchQuery": function () {},
  "_search": function () {},
  "_zip": function () {}
};
jQuery.fn.textcomplete.Dropdown.prototype = {
  "$el": function () {},
  "$inputEl": function () {},
  "completer": function () {},
  "footer": function () {},
  "header": function () {},
  "id": function () {},
  "maxCount": function () {},
  "placement": function () {},
  "shown": function () {},
  "data": function () {},
  "className": function () {},
  "destroy": function () {},
  "render": function () {},
  "setPosition": function () {},
  "clear": function () {},
  "activate": function () {},
  "deactivate": function () {},
  "isUp": function () {},
  "isDown": function () {},
  "isEnter": function () {},
  "isPageup": function () {},
  "isPagedown": function () {},
  "isEscape": function () {},
  "_data": function () {},
  "_index": function () {},
  "_$header": function () {},
  "_$noResultsMessage": function () {},
  "_$footer": function () {},
  "_bindEvents": function () {},
  "_onClick": function () {},
  "_onMouseover": function () {},
  "_onKeydown": function () {},
  "_defaultKeydown": function () {},
  "_up": function () {},
  "_down": function () {},
  "_enter": function () {},
  "_pageup": function () {},
  "_pagedown": function () {},
  "_activateIndexedItem": function () {},
  "_getActiveElement": function () {},
  "_setScroll": function () {},
  "_buildContents": function () {},
  "_renderHeader": function () {},
  "_renderFooter": function () {},
  "_renderNoResultsMessage": function () {},
  "_renderContents": function () {},
  "_fitToBottom": function () {},
  "_fitToRight": function () {},
  "_applyPlacement": function () {}
};
jQuery.fn.textcomplete.Strategy.prototype = {
  "match": function () {},
  "replace": function () {},
  "search": function () {},
  "id": function () {},
  "cache": function () {},
  "context": function () {},
  "index": function () {},
  "template": function () {},
  "idProperty": function () {}
};
jQuery.fn.textcomplete.Adapter.prototype = {
  "id": function () {},
  "completer": function () {},
  "el": function () {},
  "$el": function () {},
  "option": function () {},
  "initialize": function () {},
  "destroy": function () {},
  "select": function () {},
  "getCaretPosition": function () {},
  "focus": function () {},
  "_bindEvents": function () {},
  "_onKeyup": function () {},
  "_skipSearch": function () {}
};
jQuery.fn.textcomplete.Textarea.prototype = {
  "id": function () {},
  "completer": function () {},
  "el": function () {},
  "$el": function () {},
  "option": function () {},
  "initialize": function () {},
  "destroy": function () {},
  "select": function () {},
  "getCaretPosition": function () {},
  "focus": function () {},
  "_bindEvents": function () {},
  "_onKeyup": function () {},
  "_skipSearch": function () {},
  "getTextFromHeadToCaret": function () {},
  "_getCaretRelativePosition": function () {},
  "_calculateLineHeight": function () {}
};
jQuery.fn.textcomplete.IETextarea.prototype = {
  "id": function () {},
  "completer": function () {},
  "el": function () {},
  "$el": function () {},
  "option": function () {},
  "initialize": function () {},
  "destroy": function () {},
  "select": function () {},
  "getCaretPosition": function () {},
  "focus": function () {},
  "_bindEvents": function () {},
  "_onKeyup": function () {},
  "_skipSearch": function () {},
  "getTextFromHeadToCaret": function () {},
  "_getCaretRelativePosition": function () {},
  "_calculateLineHeight": function () {}
};
jQuery.fn.textcomplete.ContentEditable.prototype = {
  "id": function () {},
  "completer": function () {},
  "el": function () {},
  "$el": function () {},
  "option": function () {},
  "initialize": function () {},
  "destroy": function () {},
  "select": function () {},
  "getCaretPosition": function () {},
  "focus": function () {},
  "_bindEvents": function () {},
  "_onKeyup": function () {},
  "_skipSearch": function () {},
  "_getCaretRelativePosition": function () {},
  "getTextFromHeadToCaret": function () {}
};
jQuery.fn.textcomplete.CKEditor.prototype = {
  "id": function () {},
  "completer": function () {},
  "el": function () {},
  "$el": function () {},
  "option": function () {},
  "initialize": function () {},
  "destroy": function () {},
  "select": function () {},
  "getCaretPosition": function () {},
  "focus": function () {},
  "_bindEvents": function () {},
  "_onKeyup": function () {},
  "_skipSearch": function () {},
  "_getCaretRelativePosition": function () {},
  "getTextFromHeadToCaret": function () {}
};
/**********************************************************************
 * End Generated Extern for jQuery
/**********************************************************************/